INSERT INTO oficiales_negocios (apellidos, nombres, cargo, id_agencia, estado) VALUES
('Diaz Pashanase','Christian','Oficial de Negocios',24,'Activo'),
('Rivera Trinidad','Freddy','Oficial de Negocios',24,'Activo'),
('Flores Espinoza','Janett Jessica','Oficial de Negocios',24,'Activo'),
('Ajahuana Mamani','Carlos Abimael','Oficial de Negocios',38,'Activo'),
('Velasquez Rojas','Carlos Jerson','Oficial de Negocios',38,'Activo'),
('Meza Pinchi','Gino Gilmer','Oficial de Negocios',38,'Activo'),
('Leyba Aguilar','Hector Idelso','Oficial de Negocios',38,'Activo'),
('Panduro Urday','Jaysel','Oficial de Negocios',38,'Activo'),
('Caceres Duran','Lee','Oficial de Negocios',38,'Activo'),
('Saldaña Alvarado','Maria Del Carmen','Oficial de Negocios',38,'Activo'),
('Horna Lanares','Paterno','Oficial de Negocios',38,'Activo'),
('Remuzgo Guevara','Ruben','Oficial de Negocios',38,'Activo'),
('Palomino Bolivar','Ana','Oficial de Negocios',15,'Activo'),
('Prado Taquire','Susana','Oficial de Negocios',15,'Activo'),
('Cardenas Alarcon','Pierre Anderson','Oficial de Negocios',15,'Activo'),
('Zarabia Ramirez','Alipio','Oficial de Negocios',15,'Activo'),
('Morales Ancco','Herber Paul','Oficial de Negocios',15,'Activo'),
('Ñuñez Huaman','Wilzon','Oficial de Negocios',15,'Activo'),
('Espinoza Aponte','Hector Socrates','Oficial de Negocios',34,'Activo'),
('Guillen Gutierrez','Nilo','Oficial de Negocios',34,'Activo'),
('Dominguez Cartolin','Elvis Cesar','Oficial de Negocios',34,'Activo'),
('Huaman Rojas','Richard Mileño','Oficial de Negocios',34,'Activo'),
('Francia Chumpitaz','Ricardo','Oficial de Negocios',22,'Activo'),
('Patiño Huapalla','Gustavo Adolfo','Oficial de Negocios',22,'Activo'),
('Florentine Florian','Grace Ivet','Oficial de Negocios',22,'Activo'),
('Canales Bernal','Rafael','Oficial de Negocios',22,'Activo'),
('Moreno Diaz','David Alexander','Oficial de Negocios',22,'Activo'),
('Risco Vera','Juan Diego','Oficial de Negocios',22,'Activo'),
('Huamán Ponce','Leonidas Daniel','Oficial de Negocios',41,'Activo'),
('Anco Amaro','Jusmel','Oficial de Negocios',41,'Activo'),
('Gregorio Sudario','Percy','Oficial de Negocios',41,'Activo'),
('Gomez Rezza','Josue Misael','Oficial de Negocios',41,'Activo'),
('Tencera Rivera','Aldo Román','Oficial de Negocios',42,'Activo'),
('Romero Noblejas','Frankler','Oficial de Negocios',42,'Activo'),
('Tello Fundez','Max','Oficial de Negocios',42,'Activo'),
('Miguel Cruz','David Amalquio','Oficial de Negocios',42,'Activo'),
('Salvatierra De Los Rios','Maria','Oficial de Negocios',20,'Activo'),
('Yeren Saravia','Jose Antonio','Oficial de Negocios',20,'Activo'),
('Torres Rojas','Jean Carlos','Oficial de Negocios',20,'Activo'),
('Salas Cardenas','Juan Julio','Oficial de Negocios',20,'Activo'),
('Guevara Flores','Edgar Alberto','Oficial de Negocios',20,'Activo'),
('Escalaya Soto','Marcelino Alejandro','Oficial de Negocios',26,'Activo'),
('Pariona Escate','Diego Armando','Oficial de Negocios',26,'Activo'),
('Hurtado Espinoza','Martin Eduardo','Oficial de Negocios',26,'Activo'),
('Jurado Degregori','Hilda Adriana','Oficial de Negocios',26,'Activo'),
('Sotelo Arcos','Andres Francisco','Oficial de Negocios',26,'Activo'),
('Chiclla Navarro','Miguel Angel','Oficial de Negocios',26,'Activo'),
('Perez Lope','Fernando','Oficial de Negocios',26,'Activo'),
('Tejada Ronceros','Halbert','Oficial de Negocios',26,'Activo'),
('Gaza Chinchay','Angel','Oficial de Negocios',32,'Activo'),
('Osores Berrocal','Lida Luz','Oficial de Negocios',32,'Activo'),
('Sehuincha Rojas','Jhonny','Oficial de Negocios',32,'Activo'),
('Jaime Chavez','Aaron','Oficial de Negocios',32,'Activo'),
('Alvarez Quispe','Jose Luis','Oficial de Negocios',32,'Activo'),
('Saez Huaman','Cesar','Oficial de Negocios',32,'Activo'),
('Palomino Yañac','Mayli','Oficial de Negocios',32,'Activo'),
('Cordova Rojas','Holaf','Oficial de Negocios',30,'Activo'),
('Vasquez Pizarro','Renato','Oficial de Negocios',30,'Activo'),
('Vargas Ticse','Abigail','Oficial de Negocios',30,'Activo'),
('Lolay Albornoz','Miriam','Oficial de Negocios',30,'Activo'),
('Garcia Surichaqui','Nelcy','Oficial de Negocios',35,'Activo'),
('Camayo Sedano','Hector','Oficial de Negocios',35,'Activo'),
('Vidal Untiveros','Roger','Oficial de Negocios',35,'Activo'),
('Paitan Ramos','Martin','Oficial de Negocios',35,'Activo'),
('Atao Tello','Mario','Oficial de Negocios',35,'Activo'),
('Quispe Ayquipa','Gladys Marleny','Oficial de Negocios',35,'Activo'),
('Bendezu Aristizabal','Luis Fernando','Oficial de Negocios',35,'Activo'),
('Hilario Villar','Wider','Oficial de Negocios',35,'Activo'),
('Torres Fernandez','Luis','Oficial de Negocios',35,'Activo'),
('Laura Soto','Brandon','Oficial de Negocios',35,'Activo'),
('Muñoz Hurtado','Bebeto','Oficial de Negocios',35,'Activo'),
('Bonzano Del Aguila','Erick Hugo','Oficial de Negocios',33,'Activo'),
('Villanueva Rengifo','Nancy Iveth','Oficial de Negocios',33,'Activo'),
('Gonzales Arevalo','Javier','Oficial de Negocios',33,'Activo'),
('Alarcon Rengifo','Patrick Kluiver','Oficial de Negocios',33,'Activo'),
('Gamonal Gonzales','Wilford Gerson','Oficial de Negocios',33,'Activo'),
('Bernardo Santos','Sofia Nelly','Oficial de Negocios',33,'Activo'),
('Ruiz Artica','Jose Luis','Oficial de Negocios',33,'Activo'),
('Nolasco Montoya','Dicna Marleni','Oficial de Negocios',31,'Activo'),
('Dominguez Rodriguez','Rosa','Oficial de Negocios',31,'Activo'),
('Cardenas Amasifuen','Linda Maela','Oficial de Negocios',27,'Activo'),
('García Tafur','Paul Alexis','Oficial de Negocios',27,'Activo'),
('Paredes Chavez','Guillermo','Oficial de Negocios',27,'Activo'),
('Flores Panaifo','Mayer','Oficial de Negocios',27,'Activo'),
('Espinoza Haro','Lesly','Oficial de Negocios',19,'Activo'),
('Hilario Ortega','Marcelo','Oficial de Negocios',19,'Activo'),
('Vega Bustamante','Luis','Oficial de Negocios',19,'Activo'),
('Palacios Torre','Ronald','Oficial de Negocios',19,'Activo'),
('Farfan Zapata','Javier','Oficial de Negocios',19,'Activo'),
('Cruz Sanchez','Juan','Oficial de Negocios',19,'Activo'),
('Yaipen Ayasta','Jenni','Oficial de Negocios',19,'Activo'),
('Baltazar Francisco','Jose','Oficial de Negocios',19,'Activo'),
('Arevalo Guerra','Ketty','Oficial de Negocios',36,'Activo'),
('Ibarra Espinoza','Juan','Oficial de Negocios',36,'Activo'),
('Yahuana Rojas','Roberto','Oficial de Negocios',36,'Activo'),
('Calle Neira','Jorge','Oficial de Negocios',36,'Activo'),
('Diaz Lizama','Karen','Oficial de Negocios',36,'Activo'),
('Nizama Sandoval','Cristhian','Oficial de Negocios',36,'Activo'),
('Temoche Yovera','Jessica','Oficial de Negocios',36,'Activo'),
('Vargas Guaylupo','Patricia','Oficial de Negocios',36,'Activo'),
('Yarleque Navarro','Mariel','Oficial de Negocios',36,'Activo'),
('Tapia Pacheco','Roberto Julio','Oficial de Negocios',28,'Activo'),
('Cordova Rojas','Jorge Walter','Oficial de Negocios',28,'Activo'),
('Vasquez Vasquez','Elicida','Oficial de Negocios',28,'Activo'),
('Perez Cervera','Diana Carolina','Oficial de Negocios',28,'Activo'),
('Guevara Milian','Tania Maria','Oficial de Negocios',28,'Activo'),
('Herrera Yajahuanca','Mariela','Oficial de Negocios',28,'Activo'),
('Cervera Hoyos','Dilmer','Oficial de Negocios',28,'Activo'),
('Ruiz Colunche','William','Oficial de Negocios',28,'Activo'),
('Saavedra Huaman','Reinerio','Oficial de Negocios',28,'Activo'),
('Chavez Correa','Percy Edgar','Oficial de Negocios',43,'Activo'),
('Arevalo Ocampo','Piero Arturo','Oficial de Negocios',43,'Activo'),
('Zurita Zurita','Omer','Oficial de Negocios',43,'Activo'),
('Chavez Cubas','Yomer','Oficial de Negocios',43,'Activo'),
('Lucana Rojas','Beatriz','Oficial de Negocios',43,'Activo'),
('Mac Valdivieso','Luis Alonso','Oficial de Negocios',39,'Activo'),
('Verde Rosas','Miguel Ángel','Oficial de Negocios',39,'Activo'),
('Sandoval Carlin','Jose Ricardo','Oficial de Negocios',40,'Activo'),
('Noblecilla Romero','Julio','Oficial de Negocios',40,'Activo'),
('Galvez Soldado','Jhony','Oficial de Negocios',40,'Activo'),
('Damian Reynoso','Luis','Oficial de Negocios',40,'Activo'),
('Curay Luna','Lily','Oficial de Negocios',40,'Activo'),
('Wong Castillo','Ricardo','Oficial de Negocios',18,'Activo'),
('Baquedano Guevara','Alex','Oficial de Negocios',18,'Activo'),
('Lora León','Javier','Oficial de Negocios',18,'Activo'),
('Cieza Maco','Naydú','Oficial de Negocios',18,'Activo'),
('Tingal Dávila','Omero','Oficial de Negocios',18,'Activo'),
('Zúñiga Rivera','Henry','Oficial de Negocios',18,'Activo'),
('Guevara Campos','Alfredo','Oficial de Negocios',18,'Activo'),
('Madrid Atalaya','Juan','Oficial de Negocios',18,'Activo'),
('Villaloboshernandez','Hugo','Oficial de Negocios',18,'Activo'),
('Fernandez Irigoyen','Alexis','Oficial de Negocios',18,'Activo'),
('Villanueva Rengifo','Fredy','Oficial de Negocios',18,'Activo'),
('Niño Sanchez','Lizbeth','Oficial de Negocios',18,'Activo'),
('Alcalde Sarmiento','Artemio','Oficial de Negocios',18,'Activo'),
('Alvarado Purisaca','José','Oficial de Negocios',18,'Activo'),
('Clavijo Puelles','Adrián','Oficial de Negocios',18,'Activo'),
('Caman Oyarce','Nelvil','Oficial de Negocios',17,'Activo'),
('Mendoza Alvarado','Jherferson','Oficial de Negocios',17,'Activo'),
('Chuquizuta Torres','Charlot','Oficial de Negocios',17,'Activo'),
('Quintana Tuanama','Leidy','Oficial de Negocios',17,'Activo'),
('Viena Panduro','Alan','Oficial de Negocios',37,'Activo'),
('Inga Julca','Gianmarco','Oficial de Negocios',37,'Activo'),
('Rojas Guevara','Jamer','Oficial de Negocios',37,'Activo'),
('Del Aguila Davila','Lauro','Oficial de Negocios',37,'Activo'),
('Baca Medina','Marcos','Oficial de Negocios',37,'Activo'),
('Cruz Cruz','Marino','Oficial de Negocios',37,'Activo'),
('Palomino Correa','Nilson','Oficial de Negocios',37,'Activo'),
('Cuenca Ramirez','Renzo','Oficial de Negocios',37,'Activo'),
('Sanchez Tinoco','William','Oficial de Negocios',37,'Activo'),
('Del Castillo Perez','Willy','Oficial de Negocios',37,'Activo'),
('Zuñiga Juape','Yhoyser','Oficial de Negocios',37,'Activo'),
('Rodriguez Tello','Davis','Oficial de Negocios',29,'Activo'),
('Ruiz Saldaña','Omar','Oficial de Negocios',29,'Activo'),
('Rojas Perez','Eloy','Oficial de Negocios',29,'Activo'),
('Guevara Guevara','Richard','Oficial de Negocios',29,'Activo'),
('Gutierrez Gavidia','Neisser','Oficial de Negocios',29,'Activo'),
('Chacon Paredes','Segundo Misael','Oficial de Negocios',16,'Activo'),
('Estrada Hernandez','Jhony Paul','Oficial de Negocios',16,'Activo'),
('Goicochea Rodriguez','Karina Judith','Oficial de Negocios',16,'Activo'),
('Gutierrez Cotrina','Jeyner Percy','Oficial de Negocios',16,'Activo'),
('Huayama Coca','Nilcer','Oficial de Negocios',16,'Activo'),
('Llanos Figueroa','Willy','Oficial de Negocios',16,'Activo'),
('Morales Aredo','Alex Waldemar','Oficial de Negocios',16,'Activo'),
('Zuloeta Sanchez','Jesus Onan','Oficial de Negocios',16,'Activo'),
('Alcantara Saavedra','Joel Oscar','Oficial de Negocios',16,'Activo'),
('Diaz Araujo','Brayan Aaron','Oficial de Negocios',16,'Activo'),
('Regalado Cayotopa','César Martín','Oficial de Negocios',44,'Activo'),
('Campos Tamay','Dilmer Miler','Oficial de Negocios',44,'Activo'),
('García Vásquez','Eduard','Oficial de Negocios',44,'Activo'),
('Fustamante Herrera','Jose','Oficial de Negocios',44,'Activo'),
('Saavedra Huanambal','Karen','Oficial de Negocios',44,'Activo'),
('Palacios Bermeo','Miguel','Oficial de Negocios',44,'Activo'),
('Julon Huaman','Dany','Oficial de Negocios',44,'Activo'),
('Cóndor Cachique','Roy','Oficial de Negocios',44,'Activo'),
('Diaz Fernandez','Richard','Oficial de Negocios',44,'Activo'),
('Guarnizo Torres','Jackson','Oficial de Negocios',45,'Activo'),
('Flores Orejuela','Jonathan','Oficial de Negocios',45,'Activo'),
('Sampen Gomez','Anali','Oficial de Negocios',45,'Activo'),
('Crisanto Cruz','Victor','Oficial de Negocios',45,'Activo'),
('Vásquez Ásquez','Nicolás','Oficial de Negocios',45,'Activo'),
('Crisanto Reto','Hernán','Oficial de Negocios',45,'Activo'),
('Muñoz Cruz','Marco','Oficial de Negocios',45,'Activo'),
('Gamboa Delgado','Jenier','Oficial de Negocios',45,'Activo'),
('Rojas Terrones','Luis','Oficial de Negocios',21,'Activo'),
('Arrelucea Abanto','Exaltacion','Oficial de Negocios',21,'Activo'),
('Quispe Escalante','Noe','Oficial de Negocios',21,'Activo'),
('Peralta Sernaque','Karol','Oficial de Negocios',21,'Activo'),
('Quiroz Sanchez','Jorge','Oficial de Negocios',21,'Activo'),
('Polo Solano','Ricardo','Oficial de Negocios',21,'Activo'),
('Ventura Chamochumbi','Kevin','Oficial de Negocios',21,'Activo'),
('Castillo Inga','Isabel','Oficial de Negocios',25,'Activo'),
('Granados Milla','Kayro','Oficial de Negocios',25,'Activo'),
('Samaritano Cabello','Wilder','Oficial de Negocios',25,'Activo'),
('Angeles Cabrera','Meliza','Oficial de Negocios',25,'Activo'),
('Sotelo Alcantara','Oscar','Oficial de Negocios',25,'Activo'),
('Tuya Cordova','Karen','Oficial de Negocios',25,'Activo'),
('Cadillo Quito','Paul','Oficial de Negocios',25,'Activo'),
('Huerta Novoa','Ervin','Oficial de Negocios',25,'Activo'),
('Cerna Orellano','Lizetti','Oficial de Negocios',25,'Activo'),
('Eufracio Broncano','Dalia','Oficial de Negocios',25,'Activo'),
('Roque Pena','Edgar','Oficial de Negocios',25,'Activo'),
('Verde','Miguel','Oficial de Negocios',39,'Activo'),
('Raico Pacheco','Aleli','Oficial de Negocios',39,'Activo'),
('Miranda Huaman','Robert','Oficial de Negocios',39,'Activo'),
('Davila Leon','Luis','Oficial de Negocios',39,'Activo'),
('Mac Valdivieso','Luis','Oficial de Negocios',39,'Activo'),
('Alonso Ruiz','Maida','Oficial de Negocios',39,'Activo'),
('Carranza Rengifo','Antony','Oficial de Negocios',39,'Activo'),
('Alva Matute','Javier','Oficial de Negocios',39,'Activo'),
('Santillan Castillo','Pedro','Oficial de Negocios',39,'Activo'),
('Gutierrez Requena','Jose','Oficial de Negocios',39,'Activo');


INSERT INTO agencia (nombre_agencia, clasificacion_agencia, id_zona) VALUES
('Ayacucho', NULL, 5),
('Cajamarca', NULL, 3),
('Chachapoyas', NULL, 4),
('Chiclayo', NULL, 3),
('Chimbote', NULL, 3),
('Chincha', NULL, 1),
('Huacho', NULL, 6),
('Huancayo', NULL, 5),
('Huánuco', NULL, 6),
('Huaraz', NULL, 3),
('Ica', NULL, 1),
('Iquitos', NULL, 6),
('Jaen', NULL, 4),
('Juanjui', NULL, 4),
('La Merced', NULL, 6),
('Padre Abad', NULL, 6),
('Pampas', NULL, 6),
('Pucallpa', NULL, 6),
('San Francisco', NULL, 5),
('Satipo', NULL, 6),
('Sullana', NULL, 3),
('Tarapoto', NULL, 4),
('Tingo María', NULL, 6),
('Trujillo', NULL, 3),
('Tumbes', NULL, 3),
('Oxapampa', NULL, 6),
('Villa Rica', NULL, 6),
('Bagua', NULL, 4),
('Chota', NULL, 4),
('Chepen', NULL, 3),
('Chulucanas', NULL, 3);

INSERT INTO jefes_agencia (apellidos, nombres, id_agencia) VALUES
('Delgado Lino','Juan Carlos',24),
('Meza Gomez','Alberto',38),
('Urbina Cardenas','Roman Abel',15),
('Vizarreta Mendoza','Felix Raul',34),
('Vivar Angeles','Antonio Jesús',22),
('Llactahuaman Marcas','Luis Arturo',41),
('Cisneros Jauregui','Claudia',42),
('Reategui Franco','Edward Kooll',20),
('Montalván Uchuya','Roberto Carlos',26),
('Camarena Ramon','Luis',30),
('Pariona Villar','Romulo',35),
('Tuesta Olaya','Felix Armando',33),
('Caballero Silva','Weyder',31),
('Vasquez Arbildo','Candy',27),
('Maya Silva','Miguel',19),
('Guerrero Saucedo','Johnny',36),
('Cano Contreras','Samuel',28),
('Perez Oclocho','Norbil Alberto',43),
('Martos Linares','Clubert',39),
('Salazar Morales','Johano Nikolai',29),
('Mas Golac','Werther',37),
('Paucar Llapapasca','Luis',40),
('Castañeda Aguilar','César',18),
('Gomez Fernandez','Neyser',17),
('Saucedo Diaz','Adali',16),
('Vasquez Altamirano','Xavier',44),
('Guerrero Carrasco','Rogelio',45),
('Arellano Tejada','Jorge',21);

